/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaJNICode_Terminal */

#ifndef _Included_JavaJNICode_Terminal
#define _Included_JavaJNICode_Terminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaJNICode_Terminal
 * Method:    enableBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaJNICode_Terminal_enableBuffer
  (JNIEnv *, jclass);

/*
 * Class:     JavaJNICode_Terminal
 * Method:    disableBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaJNICode_Terminal_disableBuffer
  (JNIEnv *, jclass);

/*
 * Class:     JavaJNICode_Terminal
 * Method:    getNextChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_JavaJNICode_Terminal_getNextChar
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
